server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #添加路由器
#routes:
  #  user-service: /user/**
  #ignored-services:
  #  - consumer-service    去除不需要暴露的服务
  routes:
    item-service: /item/**
    search-service: /search/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
ribbon:
  ConnectTimeout: 350 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
#  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
#  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 # 熔断超时时长：6000ms